local monitor = peripheral.find("monitor")
term.redirect(monitor)
term.setBackgroundColor(colors.black)
term.clear()
paintutils.drawBox(0, 0, 2, 2, colors.red)
term.setCursorPos(1, 1)
sleep(2)
term.setBackgroundColor(colors.black)
term.write("Testing")